stages:
  - test
  - build
  - deploy

test:
  stage: test
  tags:
    - macos
  before_script:
    - pip install --upgrade pip && pip install hatch
  script:
    - hatch test --cover
  coverage: '/\s+(\d+%)$/'

build-stable:
  stage: build
  tags:
    - macos
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: never
  before_script:
    - pip install --upgrade pip && pip install hatch
  script:
    - hatch build -t wheel
  after_script:
    - echo "my-arithmetic-lperroud deployment on stable servers"
    - ls -l dist/
  
build-dev:
  stage: build
  tags:
    - macos
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: on_success
    - when: never
  before_script:
    - pip install --upgrade pip && pip install hatch
  script:
    - hatch build -t wheel
  after_script:
    - echo "my-arithmetic-lperroud deployment on develop servers"
    - ls -l dist/

pages:
  stage: deploy
  tags:
    - macos
  - before_script:
    - pip install --upgrade pip && pip install sphinx
  script:
    - sphinx-build -b html . public/
  artifacts:
    paths:
      - public
  only:
    - main