stages:
  - test

test:
  stage: test
  coverage: /TOTAL.*? (100(?:\.0+)?\%\|[1-9]?\d(?:\.\d+)?\%)$/
  tags:
    - macos
  before_script:
    - pip install --upgrade pip && pip install hatch pytest-cov
  script:
    - hatch test
    - pytest --cov=my_arithmetic_lperroud