stages:
  - test
  - build

test:
  stage: test
  tags:
    - macos
  before_script:
    - pip install --upgrade pip && pip install hatch
  script:
    - hatch test --cover
  coverage: '/\s+(\d+%)$/'

build:
  stage: build
  tags:
    - macos
  before_script:
    - pip install --upgrade pip && pip install hatch
  script:
    - hatch build -t wheel
  after_script:
    - echo "Files in dist for $CI_COMMIT_TAG"
    - ls -l dist/
